pipeline {
	agent any
	environment  {
		jenkinsUrl = "http://192.168.25.69:8080"
		jobName = "GIT_eSirius_build_all"
		pipelineToken = "760429"
	}
	stages {
		stage ("run") {
			steps {
				sh "wget \"${env.jenkinsUrl}/view/GIT/job/${env.jobName}/buildWithParameters?token=${env.pipelineToken}&revision=master\""
				sh "wget \"${env.jenkinsUrl}/view/GIT/job/${env.jobName}/buildWithParameters?token=${env.pipelineToken}&revision=develop\""
			}
		}
	}
}
