pipeline {
	agent any
	parameters {
		choice(name: "revision", choices: "master\ndevelop\nbuild\n", description: "branche ou TAG")
		choice(name: "mavenProfile", choices: "prod_windows\nprod_linux\ndev_windows\ndev_linux\ncd\n", description: "profile maven")
		booleanParam(name: "secondaryDeploy", defaultValue: false, description: "déployer sur les serveurs secondaires")
	}
	environment {
		depotFolder = "depot"
		gitLabUrl = "http://192.168.25.68/eSirius/"
		primaryRemote = "jenkins@192.168.25.94"
	}
	stages {
		stage ("Initialize") {
			steps {
				wrap([$class: 'AnsiColorBuildWrapper']) {
					echo "\u001B[34m revision : ${params.revision} \u001B[m"
					echo "\u001B[34m mavenProfile : ${params.mavenProfile} \u001B[m"
					echo "\u001B[34m secondaryDeploy : ${params.secondaryDeploy} \u001B[m"
				}
				cleanWs()
			}
		}
		stage ("Create data folder") {
			steps {
				sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/data/event-storage/"
			}
		}
		stage ("build groupe 1") {
			parallel {
				stage ("build es2i") {
					environment {
						gitRoot = "es2i"
						projectRoot = "es2i"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = ""
						sourceAppDirectory = ""
						sourceExtension = ""
						sourceConfDirectory = ""
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
				stage ("build eCustomer") {
					environment {
						gitRoot = "eCustomer"
						projectRoot = "eCustomer"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = "customer"
						sourceAppDirectory = "eCustomer-app/target"
						sourceExtension = ".war"
						sourceConfDirectory = "eCustomer-conf/target/eCustomer-conf"
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
				stage ("build smsSender") {
					environment {
						gitRoot = "smsSender"
						projectRoot = "smsSender"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = "smssender"
						sourceAppDirectory = "smsSender-app/target"
						sourceExtension = ".war"
						sourceConfDirectory = "smsSender-conf/target/smsSender-conf"
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
				stage ("build procyon") {
					environment {
						gitRoot = "eStat"
						projectRoot = "procyon"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = ""
						sourceAppDirectory = ""
						sourceExtension = ""
						sourceConfDirectory = ""
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
			}
		}
		stage ("build eSecurity") {
			environment {
				gitRoot = "eSecurity"
				projectRoot = "esecurity"
				jdkCompilation = "JDK 1.6.0_20"
				mvnVersion = "Maven 3.2.1"
				targetDirectory = "esecurity"
				sourceAppDirectory = "esecurity-gxt-app/target"
				sourceExtension = ".war"
				sourceConfDirectory = "esecurity-conf/target/esecurity-conf"
				sourceConfDirectory1 = "esecurity-gxt-conf/target/esecurity-gxt-conf"
			}
			steps {
				sh "mkdir -p ${env.gitRoot}"
				dir ("${env.gitRoot}") {
					cleanProjectPrimaryRemote(env.targetDirectory)
					runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
					
					sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
					deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
					
					sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
					deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
					deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory1)
				}
			}
		}
		stage ("build groupe 3") {
			parallel {
				stage ("build eSirius-shared") {
					environment {
						gitRoot = "eSirius"
						projectRoot = "eSirius-shared"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = ""
						sourceAppDirectory = ""
						sourceExtension = ""
						sourceConfDirectory = ""
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
				stage ("build eStat") {
					environment {
						gitRoot = "eStat"
						projectRoot = "eSirius-estat"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = "estat"
						sourceAppDirectory = "eSirius-estat-app/target"
						sourceExtension = ".war"
						sourceConfDirectory = "eStatConf/target/eStat-conf"
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
			}
		}
		stage ("build groupe 4") {
			parallel {
				stage ("build History") {
					environment {
						gitRoot = "History"
						projectRoot = "eSirius-history"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = "esirius-history-event"
						sourceAppDirectory = "eSirius-history-event-app/target"
						sourceExtension = ".war"
						sourceConfDirectory = "eSirius-history-event-conf/target/eSirius-history-event-conf"
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
				stage ("build ePlanning") {
					environment {
						gitRoot = "ePlanning"
						projectRoot = "ePlanning"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = "ePlanning"
						sourceAppDirectory = "ePlanning-app/target"
						sourceExtension = ".war"
						sourceConfDirectory = "ePlanningConf/target/ePlanningConf"
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
			}
		}
		stage ("build groupe 5") {
			parallel {
				stage ("build eSirius") {
					environment {
						gitRoot = "eSirius"
						projectRoot = "eSirius"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = "eSirius"
						sourceAppDirectory = "eSirius-app/target"
						sourceExtension = ".war"
						sourceConfDirectory = "eSiriusConf/target/eSirius-Conf"
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
				stage ("build Appointment") {
					environment {
						gitRoot = "Appointment"
						projectRoot = "appointment"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = "appointment"
						sourceAppDirectory = "appointment-app/target"
						sourceExtension = ".war"
						sourceConfDirectory = "appointment-conf/target/appointment-conf"
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
			}
		}
		stage ("build groupe 6") {
			parallel {
				stage ("build eAdmin") {
					environment {
						gitRoot = "eAdmin"
						projectRoot = "eSirius-admin"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = "eadmin"
						sourceAppDirectory = "eSirius-admin-app/target"
						sourceExtension = ".war"
						sourceConfDirectory = "eSirius-admin-conf/target/eSirius-admin-conf"
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
				stage ("build eVision") {
					environment {
						gitRoot = "eVision"
						projectRoot = "eSirius-vision"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						targetDirectory = "evision"
						sourceAppDirectory = "eSirius-vision-app/target"
						sourceExtension = ".war"
						sourceConfDirectory = "eSirius-vision-conf/target/eSirius-vision-conf"
					}
					steps {
						sh "mkdir -p ${env.gitRoot}"
						dir ("${env.gitRoot}") {
							cleanProjectPrimaryRemote(env.targetDirectory)
							runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension, env.sourceConfDirectory)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
							deployApp(env.projectRoot, env.targetDirectory, env.sourceAppDirectory, env.sourceExtension)
							
							sh "ssh ${env.primaryRemote} mkdir -p ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
							deployConf(env.projectRoot, env.targetDirectory, env.sourceConfDirectory)
						}
					}
				}
			}
		}
		stage ("secondary deploy") {
			steps {
				script {
					if (params.secondaryDeploy) {
						sh "ssh ${env.primaryRemote} \"cd ${env.depotFolder}/${params.revision}/${params.mavenProfile} && tar -cf ESII-Applications.gz ESII-Applications\""
						deployToSecondaryRemote("jenkins@192.168.25.22")
						sh "ssh ${env.primaryRemote} rm -rf ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications.gz"
					}
				}
			}
		}
	}
}

void runBuild(String gitRoot, String projectRoot, String jdkCompilation, String mvnVersion, String targetDirectory, String sourceAppDirectory, String sourceExtension, String sourceConfDirectory) {
	sh "mkdir -p ${gitRoot}"
	checkoutRevisionOnRepo(gitRoot)
	dir ("${projectRoot}") {
		mvnCleanInstall(projectRoot, jdkCompilation, mvnVersion)
	}
}

void checkoutRevisionOnRepo(String gitRoot) {
	checkout scm: [ $class: "GitSCM", 
					userRemoteConfigs: [ [url: env.gitLabUrl+gitRoot, credentialsId: "root"] ],
					branches: [ [name: params.revision] ]
				  ], poll: false
}

void mvnCleanInstall(String projectRoot, String jdkCompilation, String mvnVersion) {
	withMaven (jdk: jdkCompilation, maven: mvnVersion) {
		sh "mvn clean install -P ${params.mavenProfile}"
	}
}

void cleanPrimaryRemote() {
	sh "ssh ${env.primaryRemote} rm -rf ${env.depotFolder}/${params.revision}/${params.mavenProfile}"
}

void cleanProjectPrimaryRemote(String targetDirectory) {
	script {
		if (targetDirectory && targetDirectory != "") { 
			sh "ssh ${env.primaryRemote} rm -rf ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${targetDirectory}" 
			sh "ssh ${env.primaryRemote} rm -rf ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${targetDirectory}" 
		}
	}
}
				
void deployApp(String projectRoot, String targetDirectory, String sourceAppDirectory, String sourceExtension) {
	script {
		if (targetDirectory && targetDirectory != "") {
			if (sourceAppDirectory && sourceAppDirectory != "") {
				sh "scp ${projectRoot}/${sourceAppDirectory}/*${sourceExtension} ${env.primaryRemote}:${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${targetDirectory}"
				sh returnStatus: true, script: "ssh ${env.primaryRemote} unzip -qq -o ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${targetDirectory}/*${sourceExtension} -d ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${targetDirectory}/"
				sh "ssh ${env.primaryRemote} rm -f ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${targetDirectory}/*${sourceExtension}"
			}
			else {
				sh "ssh ${env.primaryRemote} rm -rf ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/app/${env.targetDirectory}"
			}
		}
	}
}

void deployConf(String projectRoot, String targetDirectory, String sourceConfDirectory) {
	script {
		if (targetDirectory && targetDirectory != "") {
			if (sourceConfDirectory && sourceConfDirectory != "") {
				sh "scp -r ${projectRoot}/${sourceConfDirectory}/* ${env.primaryRemote}:${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${targetDirectory}"
			}
			else {
				sh "ssh ${env.primaryRemote} rm -rf ${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications/conf/${env.targetDirectory}"
			}
		}
	}
}

void deployToSecondaryRemote(String secondaryRemote) {
	sh "ssh ${secondaryRemote} \"rm -rf ESII-Applications && mkdir -p ESII-Applications\""
	
	sh "scp -r ${env.primaryRemote}:${env.depotFolder}/${params.revision}/${params.mavenProfile}/ESII-Applications.gz ${secondaryRemote}:"
	sh "ssh ${secondaryRemote} tar -xf ESII-Applications.gz"
	
	sh "ssh ${secondaryRemote} rm -rf ESII-Applications.gz"
}