pipeline {
	agent any
	parameters {
		string(name: "revision", defaultValue: "master", description: "branche ou TAG")
	}
	environment {
		depotFolder = "depot"
		esiiAppFolder = "ESII-APPLICATION/app"
		esiiConfFolder = "ESII-APPLICATION/conf"
		gitLabUrl = "http://192.168.25.68/eSirius/"
		remoteConnexion = "esii@192.168.25.94"
	}
	stages {
		stage ("Initialize") {
			steps {
				wrap([$class: 'AnsiColorBuildWrapper']) {
					echo "\u001B[34m revision : ${params.revision} \u001B[m"
				}
				cleanWs()
				sh "ssh ${env.remoteConnexion} rm -rf ${env.depotFolder}/${params.revision}"
			}
		}
		stage ("build groupe 1") {
			parallel {
				stage ("build es2i") {
					environment {
						gitRoot = "es2i"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "es2i"
						sourceAppDirectory = ""
						sourceConfDirectory = ""
						targetDirectory = ""
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
				stage ("build eCustomer") {
					environment {
						gitRoot = "eCustomer"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "eCustomer"
						sourceAppDirectory = "eCustomer-app/target"
						sourceConfDirectory = "eCustomer-conf/target/eCustomer-conf"
						targetDirectory = "customer"
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
				stage ("build smsSender") {
					environment {
						gitRoot = "smsSender"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "smsSender"
						sourceAppDirectory = "smsSender-app/target"
						sourceConfDirectory = "smsSender-conf/target/smsSender-conf"
						targetDirectory = "smssender"
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
				stage ("build procyon") {
					environment {
						gitRoot = "eStat"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "procyon"
						sourceAppDirectory = ""
						sourceConfDirectory = ""
						targetDirectory = ""
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
			}
		}
		stage ("build eSecurity") {
			environment {
				gitRoot = "eSecurity"
				jdkCompilation = "JDK 1.6.0_20"
				mvnVersion = "Maven 3.2.1"
				projectRoot = "esecurity"
				sourceAppDirectory = "esecurity-gxt-app/target"
				sourceConfDirectory = "esecurity-conf/target/esecurity-conf"
				targetDirectory = "esecurity"
			}
			steps {
				runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
			}
		}
		stage ("build groupe 3") {
			parallel {
				stage ("build eSirius-shared") {
					environment {
						gitRoot = "eSirius"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "eSirius-shared"
						sourceAppDirectory = ""
						sourceConfDirectory = ""
						targetDirectory = ""
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
				stage ("build es2i-rsi-connector") {
					environment {
						gitRoot = "es2i-rsi-connector"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "es2i-rsi-connector"
						sourceAppDirectory = ""
						sourceConfDirectory = ""
						targetDirectory = ""
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
				stage ("build eStat") {
					environment {
						gitRoot = "eStat"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "eSirius-estat"
						sourceAppDirectory = "eSirius-estat-app/target"
						sourceConfDirectory = "eStatConf/target/eStat-conf"
						targetDirectory = "estat"
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
			}
		}
		stage ("build groupe 4") {
			parallel {
				stage ("build History") {
					environment {
						gitRoot = "History"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "eSirius-history"
						sourceAppDirectory = "eSirius-history-event-app/target"
						sourceConfDirectory = "eSirius-history-event-conf/target/eSirius-history-event-conf"
						targetDirectory = "esirius-history-event"
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
				stage ("build ePlanning") {
					environment {
						gitRoot = "ePlanning"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "ePlanning"
						sourceAppDirectory = "ePlanning-app/target"
						sourceConfDirectory = "ePlanningConf/target/ePlanningConf"
						targetDirectory = "ePlanning"
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
			}
		}
		stage ("build groupe 5") {
			parallel {
				stage ("build eSirius") {
					environment {
						gitRoot = "eSirius"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "eSirius"
						sourceAppDirectory = "eSirius-app/target"
						sourceConfDirectory = "eSiriusConf/target/eSirius-Conf"
						targetDirectory = "eSirius"
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
				stage ("build Appointment") {
					environment {
						gitRoot = "Appointment"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "appointment"
						sourceAppDirectory = "appointment-app/target"
						sourceConfDirectory = "appointment-conf/target/appointment-conf"
						targetDirectory = "appointment"
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
			}
		}
		stage ("build groupe 6") {
			parallel {
				stage ("build eAdmin") {
					environment {
						gitRoot = "eAdmin"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "eSirius-admin"
						sourceAppDirectory = "eSirius-admin-app/target"
						sourceConfDirectory = "eSirius-admin-conf/target/eSirius-admin-conf"
						targetDirectory = "eadmin"
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
				stage ("build eVision") {
					environment {
						gitRoot = "eVision"
						jdkCompilation = "JDK 1.6.0_20"
						mvnVersion = "Maven 3.2.1"
						projectRoot = "eSirius-vision"
						sourceAppDirectory = "eSirius-vision-app/target"
						sourceConfDirectory = "eSirius-vision-conf/target/eSirius-vision-conf"
						targetDirectory = "evision"
					}
					steps {
						runBuild(env.gitRoot, env.projectRoot, env.jdkCompilation, env.mvnVersion, env.targetDirectory, env.sourceAppDirectory, env.sourceConfDirectory)
					}
				}
			}
		}
	}
}

void runBuild(String gitRoot, String projectRoot, String jdk, String mvn, String targetDirectory, String sourceAppDirectory, String sourceConfDirectory) {
	
	sh "mkdir -p ${gitRoot}"

	dir ("${gitRoot}") {
		checkoutRevisionOnRepo(gitRoot)
		mvnCleanInstall(projectRoot, jdk, mvn)
		deploy(projectRoot, targetDirectory, sourceAppDirectory, sourceConfDirectory)
	}
}

void checkoutRevisionOnRepo(String gitRoot) {
	script {
		try {
			checkout scm: [ $class: "GitSCM", 
							userRemoteConfigs: [ [url: env.gitLabUrl+gitRoot, credentialsId: "root"] ],
							branches: [ [name: params.revision] ]
						  ], poll: false
		}
		catch(Exception e) {
			wrap([$class: 'AnsiColorBuildWrapper']) {
				echo "\u001B[31mLa branche ou le tag '${params.revision}' n'existe pas sur le repository '${gitRoot}' => build de la branche 'master'\u001B[m"
			}
			checkout scm: [ $class: "GitSCM", 
							userRemoteConfigs: [ [url: env.gitLabUrl+gitRoot, credentialsId: "root"] ],
							branches: [ [name: 'master'] ]
						  ], poll: false
		}
	}
}

void mvnCleanInstall(String projectRoot, String jdk, String mvn) {
	dir ("${projectRoot}") {
		withMaven (jdk: jdk, maven: mvn) {
			sh "mvn clean install"
		}
	}
}

void deploy(String projectRoot, String targetDirectory, String sourceAppDirectory, String sourceConfDirectory) {

	script {
		
		if (targetDirectory && targetDirectory != "") {
			sh "ssh ${env.remoteConnexion} rm -rf ${env.depotFolder}/${params.revision}/${env.esiiAppFolder}/${targetDirectory}"
			sh "ssh ${env.remoteConnexion} rm -rf ${env.depotFolder}/${params.revision}/${env.esiiConfFolder}/${targetDirectory}"
		
			if (sourceAppDirectory && sourceAppDirectory != "") {
				sh "ssh ${env.remoteConnexion} mkdir -p ${env.depotFolder}/${params.revision}/${env.esiiAppFolder}/${targetDirectory}"
				sh "scp ${projectRoot}/${sourceAppDirectory}/*.war ${env.remoteConnexion}:${env.depotFolder}/${params.revision}/${env.esiiAppFolder}/${targetDirectory}"
				sh "ssh ${env.remoteConnexion} unzip ${env.depotFolder}/${params.revision}/${env.esiiAppFolder}/${targetDirectory}/*.war -d ${env.depotFolder}/${params.revision}/${env.esiiAppFolder}/${targetDirectory}/"
				sh "ssh ${env.remoteConnexion} rm -f ${env.depotFolder}/${params.revision}/${env.esiiAppFolder}/${targetDirectory}/*.war"
			}
			if (sourceConfDirectory && sourceConfDirectory != "") {
				sh "ssh ${env.remoteConnexion} mkdir -p ${env.depotFolder}/${params.revision}/${env.esiiConfFolder}/${targetDirectory}"
				sh "scp -r ${projectRoot}/${sourceConfDirectory}/* ${env.remoteConnexion}:${env.depotFolder}/${params.revision}/${env.esiiConfFolder}/${targetDirectory}"
			}
		}
	}
}